spring:
  h2.console:
    enabled: true
    path: "/h2"

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml

tower:
  approaching-certification-deadline: 3 //liczba dni określająca bliskość terminu ważności certyfikacji

